### ISSUE TITLE
No opening detail for states

### ISSUE THREAD

**Issue by tjmelo** [tjmelo/tmx-mercury#45]
When options detail is clicked, it does not show your details for states.
App showing a white screen.

#### Console log detail

![Screenshot from 2022-07-23 12-36-43](https://user-images.githubusercontent.com/5209592/180612015-aa9f07f1-aa5f-489c-880f-d80dbab440de.png)

**Comment by tm-wd** [comment]
Issue solved!
PR: https://github.com/tjmelo/tmx-mercury/pull/46
