### ISSUE TITLE
To fix favicon behavior path

### ISSUE THREAD

**Issue by tm-wd** [tjmelo/tmx-mercury#77]
Proposal
---
- To fix behavior favicon path. It's not showed on the browser

**Comment by tjmelo** [comment]
Fixed behavior from favicon path.

Print reference:

![Screenshot from 2024-02-02 11-41-45](https://github.com/tjmelo/tmx-mercury/assets/5209592/fddfa4b0-4cfb-49a1-92c3-39fb355f52fa)
